In [1]:
import numpy as np

# 创建一个4x6的数组并转化为float类型
t = np.arange(24).reshape(4, 6).astype('float')

# 将数组中的一部分替换为 NaN
t[1, 3:] = np.nan
print("原始数组:")
print(t)
print('-------------------')

# 遍历每一列，然后判断每一列是否有 NaN
for i in range(t.shape[1]):
    # 获取当前列数据
    temp_col = t[:, i]
    
    # 判断当前列的数据中是否含有 NaN
    nan_num = np.count_nonzero(temp_col != temp_col)
    
    # 条件成立说明含有 NaN
    if nan_num != 0:
        # 将这一列不为 NaN 的数据拿出来
        temp_col_not_nan = temp_col[temp_col == temp_col]
        
        # 将 NaN 替换成这一列的平均值
        t[:, i] = np.where(np.isnan(temp_col), np.mean(temp_col_not_nan), temp_col)

print("替换后的数组:")
print(t)


原始数组:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
替换后的数组:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = a[[True, True, False]]
print(b)


[1 2]
