In [2]:
import pandas as pd
# 通过 list 构建 Series
ser_obj = pd.Series(range(10, 20))
# print(ser_obj.head(3))
print(ser_obj)
# print(type(ser_obj))

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [5]:
# 获取数据
print(ser_obj.values)
# 获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


In [6]:
print(ser_obj * 2)
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [9]:
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print(ser_obj2.index)
print(ser_obj2[2001])

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Index([2001, 2002, 2003], dtype='int64')
17.8


In [10]:
import numpy as np
import pandas as pd
# 通过 ndarray 构建 DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4)))
print(t)
array = np.random.randn(5,4)
print(array)
df_obj = pd.DataFrame(array)
print(df_obj.head())

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
[[ 0.8030662   1.22077248  1.51287646 -0.21465482]
 [-0.82713471  1.35483708 -0.19823989  0.91070076]
 [ 0.264252   -0.58848085 -1.63562425 -0.18975253]
 [ 0.36477397 -1.47758211 -1.54430568 -1.18906409]
 [ 0.952901    1.3589144  -0.03171172 -1.47112588]]
          0         1         2         3
0  0.803066  1.220772  1.512876 -0.214655
1 -0.827135  1.354837 -0.198240  0.910701
2  0.264252 -0.588481 -1.635624 -0.189753
3  0.364774 -1.477582 -1.544306 -1.189064
4  0.952901  1.358914 -0.031712 -1.471126


In [11]:
dict_data = {'A': 1,
'B': pd.Timestamp('20190926'),
'C': pd.Series(1,index=list(range(4)),dtype='float32'),
'D': np.array([3] * 4,dtype='int32'),
'E': ["Python","Java","C++","C"],
'F': 'wangdao' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)
d1={"name":["xiaoming","xiaogang"],"age":[20,32],"tel":
[10086,10010]}
print(pd.DataFrame(d1))
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},{ "name":
"xiaogang" ,"tel": 10000} ,{"name":"xiaowang" ,"age":22}]
print(pd.DataFrame(d2))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao
       name  age    tel
0  xiaoming   20  10086
1  xiaogang   32  10010
       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
